spring:
  datasource:
    url: jdbc:postgresql://db:5432/projeto_java_foda
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Logging para desenvolvimento
logging:
  level:
    com.exemplo: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Configurações JWT
jwt:
  secret: sua-chave-secreta-super-segura-aqui-que-deve-ter-pelo-menos-256-bits
  expiration: 86400000

# Configurações do servidor
server:
  port: 8080
  servlet:
    context-path: /api 