apiVersion: apps/v1
kind: Deployment
metadata:
  name: projeto-java-foda-2025
  labels:
    app: projeto-java-foda-2025
spec:
  replicas: 3
  selector:
    matchLabels:
      app: projeto-java-foda-2025
  template:
    metadata:
      labels:
        app: projeto-java-foda-2025
    spec:
      containers:
      - name: app
        image: projeto-java-foda-2025:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-service:5432/projeto_java_foda_2025"
        - name: SPRING_REDIS_HOST
          value: "redis-service"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
        - name: SPRING_ELASTICSEARCH_URIS
          value: "http://elasticsearch-service:9200"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: projeto-java-foda-2025
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer 